const games = [
  { id: 1, name: "Cult of the lamb", price: 64.99 },
  { id: 4, name: "Hogwarts Legacy", price: 249.99 },
  { id: 5, name: "Spyro Reignited Trilogy", price: 149.9 },
  { id: 6, name: "Crash Bandicoot N.Sane Trilogy", price: 179.5 },
  { id: 7, name: "Stardew Valley", price: 24.99 },
  { id: 8, name: "Harvest Moon: Back to Nature", price: 31.9 },
  { id: 10, name: "Pokémon Legends: Arceus", price: 299.0 },
  { id: 11, name: "Super Mario 3D World + Bowser’s Fury", price: 299.0 },
  { id: 12, name: "Animal Crossing: New Horizons", price: 299.0 },
  { id: 14, name: "Untitled Goose Game", price: 34.0 },
  { id: 15, name: "Mortal Kombat", price: 39.98 },
  { id: 16, name: "My hero one's justice", price: 199.9 },
  { id: 17, name: "Genshin Impact", price: 0.0 },
  { id: 18, name: "Honkai: Star Rail", price: 0.0 },
  { id: 19, name: "Grand Theft Auto V", price: 82.42 },
  { id: 20, name: "Red Dead Redemption 2", price: 299.9 },
  { id: 21, name: "The Legend of Zelda: Breath of the Wild", price: 299.0 },
  { id: 22, name: "Slime Rancher", price: 99.5 },
  { id: 23, name: "Minecraft Dungeons", price: 83.5 },
  { id: 24, name: "Sackboy: Uma Grande Aventura", price: 299.9 },
  { id: 25, name: "Lego Indiana Jones: The Original Adventures", price: 37.99 },
  { id: 26, name: "Hi-Fi Rush", price: 109.0 },
  { id: 29, name: "The Henry Stickmin Collection", price: 28.99 },
  { id: 30, name: "Fall Guys", price: 0.0 },
  { id: 31, name: "Gang Beasts", price: 36.99 },
  { id: 32, name: "Human Fall Flat", price: 37.99 },
  { id: 33, name: "Overcooked!", price: 38.99 },
  { id: 34, name: "I Am Bread", price: 41.99 },
  { id: 35, name: "Keep Talking and Nobody Explodes", price: 46.99 },
  { id: 36, name: "House Flipper", price: 73.99 },
];

module.exports = {
  games,
};
